# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Egressor < Formula
  desc "Local-first egress monitoring and control for developer tools"
  homepage "https://github.com/ehsaniara/egressor"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/ehsaniara/egressor/releases/download/v0.1.0/egressor_0.1.0_darwin_amd64.tar.gz"
    sha256 "b8c22aa756c8ad6003a2a386665b7b64cfa6f14c99c2244231f01faf49229950"

    define_method(:install) do
      bin.install "egressor"
      pkgshare.install "config.yaml"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/ehsaniara/egressor/releases/download/v0.1.0/egressor_0.1.0_darwin_arm64.tar.gz"
    sha256 "cea6e41f8c3a53cd3240047d8e8c870a7ab63e42142227955da19cd37ece69eb"

    define_method(:install) do
      bin.install "egressor"
      pkgshare.install "config.yaml"
    end
  end

  def caveats
    <<~EOS
      Egressor will auto-create ~/.egressor/config.yaml on first run.
      To set up TLS interception, run:
        egressor --generate-ca
        sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain ~/.egressor/ca.pem
    EOS
  end

  service do
    run [opt_bin/"egressor", "--headless"]
    keep_alive true
    log_path var/"log/egressor/egressor.log"
    error_log_path var/"log/egressor/egressor-error.log"
  end
end
