# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Egressor < Formula
  desc "Local-first egress monitoring and control for developer tools"
  homepage "https://github.com/ehsaniara/egressor"
  version "0.0.5"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/ehsaniara/egressor/releases/download/v0.0.5/egressor_0.0.5_darwin_amd64.tar.gz"
    sha256 "d05d933adfde496b5c7b8278f0b5d998e54028269e359d30dad358d6f607c19b"

    define_method(:install) do
      bin.install "egressor"
      pkgshare.install "config.yaml"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/ehsaniara/egressor/releases/download/v0.0.5/egressor_0.0.5_darwin_arm64.tar.gz"
    sha256 "f5e026b3ae47a7591acb1c5dfd6339f2ccc292d9a40dea435ced1f056c890809"

    define_method(:install) do
      bin.install "egressor"
      pkgshare.install "config.yaml"
    end
  end

  def post_install
    egressor_dir = Pathname.new("#{Dir.home}/.egressor")
    egressor_dir.mkpath
    config_dest = egressor_dir/"config.yaml"
    unless config_dest.exist?
      cp pkgshare/"config.yaml", config_dest
      ohai "Config installed to #{config_dest}"
    end
  end

  service do
    run [opt_bin/"egressor", "--headless"]
    keep_alive true
    log_path var/"log/egressor/egressor.log"
    error_log_path var/"log/egressor/egressor-error.log"
  end
end
